env:
  browser: true
  es2021: true
extends: xo
overrides:
  - extends:
      - xo-typescript
      - xo-typescript/space
      - prettier
    files:
      - '*.ts'
      - '*.tsx'
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {}
